export const OPEN_POST_CREATOR = 'OPEN_POST_CREATOR';
export const CLOSE_POST_CREATOR = 'CLOSE_POST_CREATOR';
export const ADD_CIRCLE_TO_POST_CREATOR = 'ADD_CIRCLE_TO_POST_CREATOR';

export const OPEN_FEED_SELECT_MENU = 'OPEN_FEED_SELECT_MENU';
export const CLOSE_FEED_SELECT_MENU = 'CLOSE_FEED_SELECT_MENU';

export const ADD_TAG_TO_POST_CREATOR = 'ADD_TAG_TO_POST_CREATOR';
export const DELETE_TAG_FROM_POST_CREATOR = 'DELETE_TAG_FROM_POST_CREATOR';

export const CREATE_POST = 'CREATE_POST';
export const CREATING_POST = 'CREATING_POST';
export const FAIL_CREATING_POST = 'FAIL_CREATING_POST';
export const CHANGE_CONTENT_ON_POST_CREATOR = 'CHANGE_CONTENT_ON_POST_CREATOR';

export const TOGGLE = 'TOGGLE';